version: '3.8'

services:
  front:
    build: 
      context: front
      dockerfile: Dockerfile.dev
    ports:
      - "5000:4200"

  back:
    build: 
      context: back
      dockerfile: Dockerfile.dev
    ports:
      - "3000:80"
    volumes:
      - ./back/src:/app/src
    environment:
      - MONGO_URI=mongodb://mongodb:27017/
      - MONGO_DB=td7
    depends_on:
      - mongodb

  reverse-proxy:
    restart: always
    build:
      context: reverse-proxy/
      dockerfile: ./Dockerfile.dev
    depends_on:
      - back
      - front
    volumes:
      - ./reverse-proxy/log:/var/log/nginx
    ports:
      - 8080:80

  mongodb:
    image: mongo
    environment:
      - MONGO_INITDB_DATABASE=td7
    volumes:
      - mongodb_data:/data/db

volumes:
  mongodb_data:


